// All reusable variables here
#let myName = "Francesco Protopapa"
#let myMatricola = "2079466"
#let myTitle = "Using uniqueness annotations to formally verify Kotlin code with Viper"
#let myDegree = "Master's Thesis"
#let myUni = "Università degli studi di Padova"
#let myDepartment = "Department of Mathematics ''Tullio Levi-Civita''"
#let myFaculty = "Master's degree in Computer Science"
#let profTitle = "Prof. "
#let myProf = "Francesco Ranzato"
#let myCompany = "Nome azienda"
#let myTutor = "Nome Cognome"
#let myLocation = "Padova"
#let myAA = "2023-2024"
#let myTime = "September 2024"