// All reusable variables here
#let myLang = "en"
#let myName = "Francesco Protopapa"
#let myMatricola = "2079466"
#let myTitle = "Verifying Kotlin Code with Viper\nby Controlling Aliasing"
#let myDegree = "Master's Thesis"
#let myUni = "Università degli studi di Padova"
#let myDepartment = "Department of Mathematics “Tullio Levi-Civita”"
#let myFaculty = "Master's degree in Computer Science"
#let profTitle = "Prof. "
#let myProf = "Francesco Ranzato"
#let myCompany = "Nome azienda"
#let myTutor = "Nome Cognome"
#let myLocation = "Padua"
#let myAA = "2023-2024"
#let myTime = "September 2024"